-- MySQL Script generated by MySQL Workbench
-- Sun May 20 19:15:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Airline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Airline` ;

-- -----------------------------------------------------
-- Schema Airline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Airline` DEFAULT CHARACTER SET utf8 ;
USE `Airline` ;

-- -----------------------------------------------------
-- Table `Airline`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Airport` (
  `airport_id` VARCHAR(3) NOT NULL,
  `airport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airport_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Airline` (
  `airline_id` VARCHAR(45) NOT NULL,
  `airline_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airline_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Passenger` (
  `passenger_id` INT NOT NULL,
  `passenger_nacionality` VARCHAR(45) NOT NULL,
  `passenger_name` VARCHAR(45) NOT NULL,
  `passenger_birthday` DATE NOT NULL,
  `passenger_sex` VARCHAR(45) NOT NULL,
  `flights_transfer` TINYINT(1) NOT NULL,
  `luggage` TINYINT(1) NOT NULL,
  PRIMARY KEY (`passenger_id`, `passenger_nacionality`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Employee` (
  `employee_id` INT NOT NULL,
  `employee_nacionality` VARCHAR(45) NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_birthday` DATE NOT NULL,
  `employee_sex` VARCHAR(45) NOT NULL,
  `employee_occupation` VARCHAR(45) NOT NULL,
  `Airline_airline_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`, `employee_nacionality`, `Airline_airline_id`),
  CONSTRAINT `fk_Employee_Airline`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `Airline`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Employee_Airline_idx` ON `Airline`.`Employee` (`Airline_airline_id` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Airplane` (
  `airplane_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  `Airline_airline_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airplane_id`, `Airline_airline_id`),
  CONSTRAINT `fk_Airplane_Airline1`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `Airline`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Airplane_Airline1_idx` ON `Airline`.`Airplane` (`Airline_airline_id` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Gate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Gate` (
  `gate_id` VARCHAR(45) NOT NULL,
  `gate_number` VARCHAR(45) NOT NULL,
  `Airport_airport_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`gate_id`, `Airport_airport_id`),
  CONSTRAINT `fk_Gate_Airport1`
    FOREIGN KEY (`Airport_airport_id`)
    REFERENCES `Airline`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gate_Airport1_idx` ON `Airline`.`Gate` (`Airport_airport_id` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Expected Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Expected Flight` (
  `flight_number` INT NOT NULL,
  `departure_time_exp` TIME(1) NOT NULL,
  `departure_day_of_the_week_exp` INT NOT NULL,
  `departure_week_exp` INT NOT NULL,
  `departure_year_exp` INT NOT NULL,
  `arrival_time_exp` TIME(1) NOT NULL,
  `arrival_day_of_the_week_exp` INT NOT NULL,
  `arrival_week_exp` INT NOT NULL,
  `arrival_year_exp` INT NOT NULL,
  `time_on_air_exp` TIME(1) NOT NULL,
  PRIMARY KEY (`flight_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`Real Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Real Flight` (
  `flight_id` INT NOT NULL,
  `departure_time_real` TIME(1) NOT NULL,
  `departure_day_of_week_real` INT NOT NULL,
  `departure_week_real` INT NOT NULL,
  `departure_year_real` INT NOT NULL,
  `arrival_time_real` TIME(1) NOT NULL,
  `departure_delay` TIME(1) NOT NULL,
  `arrival_day_of_week_real` INT NOT NULL,
  `arrival_week_real` INT NOT NULL,
  `arrival_yera_real` INT NOT NULL,
  `time_on_air_real` TIME(1) NOT NULL,
  `arrival_delay` TIME(1) NOT NULL,
  `ticket_loss` INT NOT NULL,
  `lost_stuff` INT NOT NULL,
  `Airplane_airplane_id` INT NOT NULL,
  `Airplane_Airline_airline_id` VARCHAR(45) NOT NULL,
  `Airline_airline_id` VARCHAR(45) NOT NULL,
  `Gate_gate_id` VARCHAR(45) NOT NULL,
  `Gate_Airport_airport_id` VARCHAR(3) NOT NULL,
  `Gate_gate_id1` VARCHAR(45) NOT NULL,
  `Gate_Airport_airport_id1` VARCHAR(3) NOT NULL,
  `Expected Flight_flight_number` INT NOT NULL,
  PRIMARY KEY (`flight_id`, `Airplane_airplane_id`, `Airplane_Airline_airline_id`, `Airline_airline_id`, `Gate_gate_id`, `Gate_Airport_airport_id`, `Gate_gate_id1`, `Gate_Airport_airport_id1`, `Expected Flight_flight_number`),
  CONSTRAINT `fk_Flight_Airplane1`
    FOREIGN KEY (`Airplane_airplane_id` , `Airplane_Airline_airline_id`)
    REFERENCES `Airline`.`Airplane` (`airplane_id` , `Airline_airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `Airline`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Real Flight_Gate1`
    FOREIGN KEY (`Gate_gate_id` , `Gate_Airport_airport_id`)
    REFERENCES `Airline`.`Gate` (`gate_id` , `Airport_airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Real Flight_Gate2`
    FOREIGN KEY (`Gate_gate_id1` , `Gate_Airport_airport_id1`)
    REFERENCES `Airline`.`Gate` (`gate_id` , `Airport_airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Real Flight_Expected Flight1`
    FOREIGN KEY (`Expected Flight_flight_number`)
    REFERENCES `Airline`.`Expected Flight` (`flight_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Flight_Airplane1_idx` ON `Airline`.`Real Flight` (`Airplane_airplane_id` ASC, `Airplane_Airline_airline_id` ASC);

CREATE INDEX `fk_Flight_Airline1_idx` ON `Airline`.`Real Flight` (`Airline_airline_id` ASC);

CREATE INDEX `fk_Real Flight_Gate1_idx` ON `Airline`.`Real Flight` (`Gate_gate_id` ASC, `Gate_Airport_airport_id` ASC);

CREATE INDEX `fk_Real Flight_Gate2_idx` ON `Airline`.`Real Flight` (`Gate_gate_id1` ASC, `Gate_Airport_airport_id1` ASC);

CREATE INDEX `fk_Real Flight_Expected Flight1_idx` ON `Airline`.`Real Flight` (`Expected Flight_flight_number` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Ticket_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Ticket_price` (
  `ticket_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`ticket_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Ticket` (
  `Airline_airline_id` VARCHAR(45) NOT NULL,
  `Passenger_passenger_id` INT NOT NULL,
  `Passenger_passenger_nacionality` VARCHAR(45) NOT NULL,
  `Ticket_price_ticket_id` INT NOT NULL,
  PRIMARY KEY (`Airline_airline_id`, `Passenger_passenger_id`, `Passenger_passenger_nacionality`, `Ticket_price_ticket_id`),
  CONSTRAINT `fk_Ticket_Airline1`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `Airline`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_passenger_id` , `Passenger_passenger_nacionality`)
    REFERENCES `Airline`.`Passenger` (`passenger_id` , `passenger_nacionality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Ticket_price1`
    FOREIGN KEY (`Ticket_price_ticket_id`)
    REFERENCES `Airline`.`Ticket_price` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ticket_Airline1_idx` ON `Airline`.`Ticket` (`Airline_airline_id` ASC);

CREATE INDEX `fk_Ticket_Passenger1_idx` ON `Airline`.`Ticket` (`Passenger_passenger_id` ASC, `Passenger_passenger_nacionality` ASC);

CREATE INDEX `fk_Ticket_Ticket_price1_idx` ON `Airline`.`Ticket` (`Ticket_price_ticket_id` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Complaint` (
  `complaint_id` INT NOT NULL,
  `date_issue` DATE NOT NULL,
  `Employee_employee_id` INT NOT NULL,
  `Employee_employee_nacionality` VARCHAR(45) NOT NULL,
  `Employee_Airline_airline_id` VARCHAR(45) NOT NULL,
  `Passenger_passenger_id` INT NOT NULL,
  `Passenger_passenger_nacionality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`complaint_id`, `Employee_employee_id`, `Employee_employee_nacionality`, `Employee_Airline_airline_id`, `Passenger_passenger_id`, `Passenger_passenger_nacionality`),
  CONSTRAINT `fk_Complaint_Employee1`
    FOREIGN KEY (`Employee_employee_id` , `Employee_employee_nacionality` , `Employee_Airline_airline_id`)
    REFERENCES `Airline`.`Employee` (`employee_id` , `employee_nacionality` , `Airline_airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complaint_Passenger1`
    FOREIGN KEY (`Passenger_passenger_id` , `Passenger_passenger_nacionality`)
    REFERENCES `Airline`.`Passenger` (`passenger_id` , `passenger_nacionality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Complaint_Employee1_idx` ON `Airline`.`Complaint` (`Employee_employee_id` ASC, `Employee_employee_nacionality` ASC, `Employee_Airline_airline_id` ASC);

CREATE INDEX `fk_Complaint_Passenger1_idx` ON `Airline`.`Complaint` (`Passenger_passenger_id` ASC, `Passenger_passenger_nacionality` ASC);


-- -----------------------------------------------------
-- Table `Airline`.`Hub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`Hub` (
  `Airline_airline_id` VARCHAR(45) NOT NULL,
  `Airport_airport_id` VARCHAR(3) NOT NULL,
  `is_hub` TINYINT(1) NULL,
  PRIMARY KEY (`Airline_airline_id`, `Airport_airport_id`),
  CONSTRAINT `fk_Hub_Airline1`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `Airline`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hub_Airport1`
    FOREIGN KEY (`Airport_airport_id`)
    REFERENCES `Airline`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hub_Airport1_idx` ON `Airline`.`Hub` (`Airport_airport_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
